# Generated by Django 3.1.5 on 2021-01-31 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_info', '0002_auto_20210115_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_from_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_no_of_emp', models.IntegerField()),
                ('max_emp_in_1slot', models.IntegerField()),
                ('min_emp_in_1slot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_slot', models.CharField(choices=[('06:00am-02:00pm', '06:00am-02:00pm'), ('02:00pm-10:00pm', '02:00pm-10:00pm'), ('10:00pm-06:00am', '10:00pm-06:00am')], max_length=15)),
                ('scheduling_day', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_info.employee')),
            ],
        ),
    ]
