# Generated by Django 3.1.5 on 2021-02-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_info', '0003_data_from_manager_scheduler'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_from_manager',
            name='store_id',
            field=models.IntegerField(default=None),
        ),
    ]
