# Generated by Django 3.1.5 on 2021-02-01 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_info', '0004_data_from_manager_store_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='preferred_slot',
        ),
        migrations.CreateModel(
            name='SlotPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_slot', models.CharField(choices=[('06:00am-02:00pm', '06:00am-02:00pm'), ('02:00pm-10:00pm', '02:00pm-10:00pm'), ('10:00pm-06:00am', '10:00pm-06:00am')], default=None, max_length=15)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_info.employee')),
            ],
        ),
    ]
