# Generated by Django 3.1.5 on 2021-02-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_info', '0005_auto_20210201_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotpreference',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
